# Generated by Django 5.2.1 on 2025-06-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReentrenamientoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('total_pacientes', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('classification_report_test', models.TextField()),
                ('confusion_matrix_test', models.JSONField()),
                ('importancia_caracteristicas', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.IntegerField(default=0)),
                ('edad', models.IntegerField()),
                ('ant_patologicos_fam', models.IntegerField(default=0)),
                ('ant_pre_peri_postnatales_positivos', models.IntegerField(default=0)),
                ('alteraciones_anatomicas', models.IntegerField(default=0)),
                ('consumo_medicamentos', models.IntegerField(default=0)),
                ('consumo_toxicos', models.IntegerField(default=0)),
                ('exp_medios_pantallas', models.IntegerField(default=0)),
                ('trastorno_neurodesarrollo', models.IntegerField(default=0)),
                ('obesidad', models.IntegerField(default=0)),
                ('hipertension_arterial', models.IntegerField(default=0)),
                ('trastornos_aprendizaje', models.IntegerField(default=0)),
                ('trastornos_comportamiento', models.IntegerField(default=0)),
                ('cefalea', models.IntegerField(default=0)),
                ('res_insulina', models.IntegerField(default=0)),
                ('depresion', models.IntegerField(default=0)),
                ('higienico_dietetico', models.IntegerField(default=0)),
                ('cognitivo_conductual', models.IntegerField(default=0)),
                ('medicamentoso', models.IntegerField(default=0)),
                ('resultado', models.IntegerField(default=0)),
                ('diagnostico_real', models.IntegerField(blank=True, null=True)),
                ('incluido_en_reentrenamiento', models.BooleanField(default=None, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
