# Generated by Django 5.2.1 on 2025-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='confianza_prediccion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
